# CMake Toolchain Profile for Windows ARM64 (WoA)
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ARM64)

# Detect available cross-compiler (LLVM-MinGW or MinGW-w64 ARM64)
find_program(_woa_clang aarch64-w64-mingw32-clang)
find_program(_woa_gcc aarch64-w64-mingw32-gcc)
find_program(_woa_clangxx aarch64-w64-mingw32-clang++)
find_program(_woa_gxx aarch64-w64-mingw32-g++)
find_program(_woa_windres aarch64-w64-mingw32-windres)
find_program(_woa_llvm_rc llvm-rc)

if(NOT CMAKE_C_COMPILER)
    if(_woa_clang)
        set(CMAKE_C_COMPILER aarch64-w64-mingw32-clang)
    elseif(_woa_gcc)
        set(CMAKE_C_COMPILER aarch64-w64-mingw32-gcc)
    else()
        set(CMAKE_C_COMPILER aarch64-w64-mingw32-gcc)
    endif()
endif()

if(NOT CMAKE_CXX_COMPILER)
    if(_woa_clangxx)
        set(CMAKE_CXX_COMPILER aarch64-w64-mingw32-clang++)
    elseif(_woa_gxx)
        set(CMAKE_CXX_COMPILER aarch64-w64-mingw32-g++)
    else()
        set(CMAKE_CXX_COMPILER aarch64-w64-mingw32-g++)
    endif()
endif()

if(NOT CMAKE_RC_COMPILER)
    if(_woa_windres)
        set(CMAKE_RC_COMPILER aarch64-w64-mingw32-windres)
    elseif(_woa_llvm_rc)
        set(CMAKE_RC_COMPILER llvm-rc)
    else()
        set(CMAKE_RC_COMPILER aarch64-w64-mingw32-windres)
    endif()
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
